# Use an official Node.js 16.19-alpine runtime as a parent image
FROM node:16.19-alpine

# Define build-time variable
ARG MONGO_CONNECTION_STRING
ARG PORT
ARG ACCESS_TOKEN_SECRET
ARG REFRESH_TOKEN_SECRET
ARG TEST_PORT
ARG MONGO_CONNECTION_STRING_TEST_DB
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_BUCKET_NAME
ARG AWS_BUCKET_REGION
ARG JWT_KEY
ARG EMAIL_SERVICE
ARG EMAIL_USER
ARG EMAIL_PASS
ARG EMAIL_VERIFY_LINK
ARG GOOGLE_OAUTH_CLIENT_ID

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to /app
COPY package*.json ./

# Install dependencies
RUN npm i

# Copy source code to /app
COPY . .

# remove bcrypt package
RUN npm uninstall bcrypt

# install bcrypt package
RUN npm install bcrypt

# Set environment variables
ENV MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING
ENV PORT=$PORT
ENV ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
ENV REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
ENV TEST_PORT=$TEST_PORT
ENV MONGO_CONNECTION_STRING_TEST_DB=$MONGO_CONNECTION_STRING_TEST_DB
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_BUCKET_NAME=$AWS_BUCKET_NAME
ENV AWS_BUCKET_REGION=$AWS_BUCKET_REGION
ENV JWT_KEY=$JWT_KEY
ENV EMAIL_SERVICE=$EMAIL_SERVICE
ENV EMAIL_USER=$EMAIL_USER
ENV EMAIL_PASS=$EMAIL_PASS
ENV EMAIL_VERIFY_LINK=$EMAIL_VERIFY_LINK
ENV GOOGLE_OAUTH_CLIENT_ID=$GOOGLE_OAUTH_CLIENT_ID

# Expose the port that the server listens on
EXPOSE 5000

# Start the server
CMD [ "npm", "run", "start" ]
